### ISSUE TITLE
User Journey Map

### ISSUE THREAD

**Issue by Gitosas** [zuri-training/Favicon-Gen-Team-61#10]
- [x] Task done by assignees

https://www.figma.com/file/xluCIzUNDGtsdNn3EAfwdF/USER-JOURNEY-MAP-TEAM_61?node-id=0%3A1

**Comment by ChinemeremChukwudire** [comment]
Persona, user story, empathy map, and User journey map drafted and completed. Available on general Figma board

**Comment by AdefolahanOmoloju** [comment]
Personas, user stories and user journey maps have been completed. Available on the figma file.

**Comment by Dlightcode** [comment]
Persona, user story, empathy map, and User journey map drafted and completed. Available on general Figma board
