### ISSUE TITLE
Sketches

### ISSUE THREAD

**Issue by Gitosas** [zuri-training/Favicon-Gen-Team-61#11]
- [x] Task done by

https://www.figma.com/file/KIDqedwXWSspDgTPdQTetk/Sketches?node-id=0%3A1

https://www.figma.com/file/jXsLYzntFYk2t3R0kpEPb7/Sketches?node-id=0%3A1

**Comment by Anielila** [comment]
Done  with Osas

https://www.figma.com/file/nb8Is9M0GvdSZ5xROZpe2f/Sketches-and-Design-Process?node-id=0%3A1
