### ISSUE TITLE
Registration/Sign in Page - Lo-fi wireframe

### ISSUE THREAD

**Issue by Gitosas** [zuri-training/Favicon-Gen-Team-61#14]
- [x] Task done by assignees

https://www.figma.com/file/5iuGEq9vpWQYiSQN4JNcRI/Sign-in-page%2FSign-up-page%2FForgot-password-page-Lo-fi-wireframes?node-id=0%3A1

**Comment by ChinemeremChukwudire** [comment]
Lo-fi for Registration/Sign-in page completed on general Figma board.

**Comment by Osatuyi** [comment]
Completed on figma board.

**Comment by cynthon** [comment]
Completed
