### ISSUE TITLE
Generator Page - Lo-fi wireframe 

### ISSUE THREAD

**Issue by Gitosas** [zuri-training/Favicon-Gen-Team-61#17]
- [x] Task done by assignees

https://www.figma.com/file/40GfG3PETqCms1QYDmI3eK/Generator-Page-Lofi?node-id=0%3A1

**Comment by AdefolahanOmoloju** [comment]
Lo-fi Completed

**Comment by AdefolahanOmoloju** [comment]
Dark Mode of Generator page designed.
