### ISSUE TITLE
Terms/Conditions & Privacy page - Lo-fi Wireframe

### ISSUE THREAD

**Issue by Gitosas** [zuri-training/Favicon-Gen-Team-61#18]
- [x] Task done by assignees

https://www.figma.com/file/z61idHX5WaMWCLuMbGfltR/Privacy-Policy-Page-%26-Terms-of-Use-Page-LoFi?node-id=0%3A1

**Comment by Yede0** [comment]
Terms of use/ Privacy policy completed
