### ISSUE TITLE
Best Practices for designing favicons

### ISSUE THREAD

**Issue by Gitosas** [zuri-training/Favicon-Gen-Team-61#3]
- [x] Done

https://docs.google.com/document/d/1J7jvr_cC2xHMY3fqC1iIx4ISejJeYngvs3YTUyIvJDg/edit

**Comment by Ade-tomiwa** [comment]
Tomiwa
There are various things one must put into consideration when designing a favicon, some of which are as follows;
1.	Stick to a simple colour palette
When designing a favicon, it is best to stick to a simple streamlined colour palette for the favicon. It’s too small to get colour crazy with
2.    Keep it simple and recognizable 
A favicon should be recognizable to the users and should also connect to the brand’s identity. It is advisable when creating a favicon, that ones should make use of identifiable elements such as the first letter of your brand name or a tiny mark that you use in conjunction with the brand. 
3.	Keeping Browser Compatibility in Mind:
 One important factor that most designers overlook when designing a favicon is that each browser has different requirements that it operates on. Depending on the browser you're using, the background of your tab could be black, white, or even grey. With the support of customizable themes, the background could be of any colour.
 4.	Size
 When designing a favicon, make sure the file is small, but not too small. Initially, all favicons were 16-pixel squares. That’s not the case anymore with the technological progress and more high-definition retina screens. The current standard size for most desktop browsers is 32x32, which replaces the previous 16x16 size. Still, one image can’t work on all browsers, so you will need to test it.
 Today, a wide range of browsers and operating systems support this feature, which allows different favicon file formats. They can be done in ICO, PNG, GIF, and JPEG formats, which are supported by the majority of browsers. To satisfy all of the Browser requirements, you simply need three sizes (16x16, 32x32, and 48x48 full-canvas icons) plus an a.ico file at the root of your site. For different pixel densities, three sizes are required. In case something goes wrong, a ".ico" file is required to allow the browser to locate the backup icon.

**Comment by AdefolahanOmoloju** [comment]
Research included in presentation material.

**Comment by philodesigns** [comment]
Task completed
