### ISSUE TITLE
Style Guides

### ISSUE THREAD

**Issue by Gitosas** [zuri-training/Favicon-Gen-Team-61#30]
- [x] Tasks done by assignees

https://www.figma.com/file/m7bJFJCSTaLcm7APr3gs9W/Style-Guides?node-id=0%3A1

**Comment by Dlightcode** [comment]
Style guide curated and updated. All available on the figma board. Thank you

**Comment by liziesilas** [comment]
Completed

**Comment by philodesigns** [comment]
Completed and all adjustments made.

**Comment by Anielila** [comment]
Done
