### ISSUE TITLE
Landing Page - Hi-fi Wireframes

### ISSUE THREAD

**Issue by Gitosas** [zuri-training/Favicon-Gen-Team-61#35]
- [x] Task done by assignees

https://www.figma.com/file/2VkwRHVQzGRPjvpTzJKnjo/LANDING-PAGE-HIGH-FIDELITY?node-id=0%3A1

**Comment by Dlightcode** [comment]
Task  completed. Thank You

**Comment by philodesigns** [comment]
Task Completed. Lo-Fi, Hi-Fi and Prototype
