### ISSUE TITLE
Sign in page  Hifi Wireframes

### ISSUE THREAD

**Issue by Gitosas** [zuri-training/Favicon-Gen-Team-61#38]
- [x] Tasks done by assignees

https://www.figma.com/file/7ROIRXkH1vczk64DN2bOr1/Sign-in-page%2F-Sign-up-page-%2F-Forgot-password-page-(HIFI)?node-id=0%3A1

**Comment by ChinemeremChukwudire** [comment]
Completed on figma board

**Comment by cynthon** [comment]
completed on figma

**Comment by Osatuyi** [comment]
Completed on figma board.
