### ISSUE TITLE
Documentation Page (Lofi, Hifi )

### ISSUE THREAD

**Issue by Gitosas** [zuri-training/Favicon-Gen-Team-61#52]
- [x] Task done by assignees

https://www.figma.com/file/o4y5GIMFBSftDRnjNsLyuA/Documentation-page?node-id=0%3A1

https://www.figma.com/file/o4y5GIMFBSftDRnjNsLyuA/Documentation-page?node-id=0%3A1

**Comment by Anielila** [comment]
Created the documentation in a Google docs format… and @Happiness-Taiwo  has translated it into a design page on figma
