### ISSUE TITLE
Documentation Document

### ISSUE THREAD

**Issue by Gitosas** [zuri-training/Favicon-Gen-Team-61#61]
- [x] Task done by assignees.

https://docs.google.com/document/d/1h7ol75ae1TyfFx5nAH65R7BK88G9XE1cAjl5Egf4zXs/edit?usp=sharing

**Comment by Anielila** [comment]
Done
https://docs.google.com/document/d/1h7ol75ae1TyfFx5nAH65R7BK88G9XE1cAjl5Egf4zXs/edit?usp=sharing
