### ISSUE TITLE
Brainstorming & Idea prioritization Diagram

### ISSUE THREAD

**Issue by Gitosas** [zuri-training/Favicon-Gen-Team-61#9]
- [x] Task done by assignees

https://www.figma.com/file/0WSIB3uA6NlNnvhmYq7gaI/Untitled?node-id=0%3A1

**Comment by philodesigns** [comment]
Task completed.

**Comment by cynthon** [comment]
Task completed

**Comment by liziesilas** [comment]
Completed...
